// <auto-generated />
using Employee.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee.Migrations
{
    [DbContext(typeof(EMPContext))]
    partial class EMPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee.Employee", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("employeeId");

                    b.ToTable("employee","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
